language: python
python:
  - "2.7"
install:
  - pip install requests
  - pip install sqlalchemy
script:
  - cd tests
  - python unit_mambustruct.py
  - python unit_mambuconfig.py
  - python unit_mambuutil.py
  - python unit_mambutask.py
  - python unit_mamburoles.py
  - python unit_mambuuser.py
