language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install requests
  - pip install sqlalchemy
  - pip install future
  - pip install mysqlclient
script:
  - cd tests
  - python unit_mambustruct.py
  - python unit_mambuconfig.py
  - python unit_mambuutil.py
  - python unit_mambutask.py
  - python unit_mamburoles.py
  - python unit_mambuuser.py
  - python unit_mambuloan.py
  - python unit_mambuactivity.py
  - python unit_mambubranch.py
  - python unit_mambucentre.py
